/api/v1/role/create:
 post:
    tags:
      - Role
    security:
      - bearerAuth: []
    description: Crear rol
    requestBody:
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/createRole'            
    responses:
      200:
        description: Petición exitosa
        content:
          application/json:
            schema:
              type: object
              properties:
                msj:
                  type: object
                  description: Mensaje de respuesta 
            example:
               {
                  "state": true,
                  "message": "Rol creado exitosamente"
                }
      400:
        description: Petición invalida
        content:
          application/json:
            schema:
              type: object
              properties:
                msj:
                  type: object
                  description: Mensaje de respuesta 
            example:
               {
                  "state": false,
                  "message": "Error al crear el rol"
                }



