/api/v1/role/delete/{id}:
 delete:
    tags:
      - Role
    security:
      - bearerAuth: []
    description: delete rol
    parameters:
      - in: path
        name: id
        type: number
        description: id de la pregunta a eliminar
        required: true
        schema:
          type: number
    responses:
      200:
        description: Petición exitosa
        content:
          application/json:
            schema:
              type: object
              properties:
                msj:
                  type: object
                  description: Mensaje de respuesta 
            example:
              {
                "state": true,
                "message": "Rol Eliminado con exito"
              }
      400:
        description: Petición invalida
        content:
          application/json:
            schema:
              type: object
              properties:
                msj:
                  type: object
                  description: Mensaje de respuesta 
            example:
              {
                "state": false,
                "message": "Error al eliminar el rol"
              }