/api/v1/role/update/{id}:
 put:
    tags:
      - Role
    security:
      - bearerAuth: []
    description: Actualizar rol
    parameters:
      - in: path
        name: id
        description: id del rol para editar
        type: number
        required: true
    requestBody:
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/updateRole'            
    responses:
      200:
        description: Petición exitosa
        content:
          application/json:
            schema:
              type: object
              properties:
                update:
                  type: object
                  properties:
                    name:
                      type: string
                msj:
                  type: object
                  description: Mensaje de respuesta 
            example:
              {
                "state": true,
                "message": "Rol Editado con exito"
              }
      400:
        description: Petición invalida
        content:
          application/json:
            schema:
              type: object
              properties:
                msj:
                  type: object
                  description: Mensaje de respuesta 
            example:
              {
                "state": false,
                "message": "Error al actualizar el rol"
              }



